# Generated by Django 5.0.14 on 2025-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
